description: >
  Build the application in production mode.
executor: default

parameters:
  checkout:
    description: Boolean for whether or not to checkout as a first step. Default is true.
    type: boolean
    default: true
  attach_workspace:
    description: Boolean for whether or not to attach to an existing workspace. Default is true.
    type: boolean
    default: true
  workspace_root:
    description: Workspace root path that is either an absolute path or a path relative to the working directory. Defaults to '.' (the working directory).
    type: string
    default: .

steps:
  - build
